HelpOn/Controllers/MyProfileController.cs
using HelpOn.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HelpOn.Repository;
using HelpOn.Helper;
using Dapper;

namespace HelpOn.Controllers
{
    public class MyProfileController : Controller
    {
        LoginRepository repo = new LoginRepository();
        // GET: MyProfile
        [Route("Profile")]
        public ActionResult Index()
        {
            if (SessionHelper.Islogin == false)
            {
                return Redirect("/Home");
            }
            
            CustomerModel customer = Connection.Query<CustomerModel>("ProcMaster_Customer 'GetProfile','" + SessionHelper.CustomerID + "'").FirstOrDefault();
            customer.State = new SelectList(repo.GetState(), "ID", "Name");
            return View(customer);
        }
        [Route("UpdateProfile")]
        public JsonResult UpdateProfile(CustomerModel customer)
        {
            AppTransactionMessage appTransaction = new AppTransactionMessage();
            DynamicParameters para = new DynamicParameters();
            para.Add("@Action", "insert");
            para.Add("@ID", SessionHelper.CustomerID);
            para.Add("@Name", customer.Name);
            para.Add("@Email", customer.Email);
            para.Add("@Mobile", customer.Mobile);
          
            appTransaction = Connection.ReturnList<AppTransactionMessage>("ProcMaster_Customer", para).FirstOrDefault();
            if (appTransaction.Status > 0)
            {
                para = new DynamicParameters();
                para.Add("@Action", "insert");
                para.Add("@CustomerID", SessionHelper.CustomerID);
                para.Add("@Name", customer.Name);
                para.Add("@Email", customer.Email);
                para.Add("@Mobile", customer.Mobile);
                para.Add("@StateID", customer.StateID);
                para.Add("@CityID", customer.CityID);
                para.Add("@Address", customer.Address);
                para.Add("@Pincode", customer.Pincode);
                appTransaction = Connection.ReturnList<AppTransactionMessage>("ProcManage_Address", para).FirstOrDefault();
            }
            return Json(appTransaction);

        }
        
        public JsonResult getCity(int stateId)
        {
            List<StateModel> states = repo.GetCity(stateId);
            
            return Json(states);

        }
        [Route("ChangePassword")]
        public ActionResult ChangePassword()
        {
            if (SessionHelper.Islogin == false)
            {
                return Redirect("/Home");
            }
            return PartialView("ChangePassword");
        }

        [Route("ChangePasswordSubmit")]
        public JsonResult ChangePasswordSubmit(ChangePasswordModel changePassword)
        {
            AppTransactionMessage appTransaction = new AppTransactionMessage();
            if ((Connection.ExecuteScalar<string>("select Password from tblMaster_Customer where ID='" + HelpOn.Helper.SessionHelper.CustomerID + "'")) != changePassword.OldPassword)
            {
                appTransaction.Status = 0;
                appTransaction.Message = "OLD Password Invalid";
                return Json(appTransaction);
            }
            else if (changePassword.password != changePassword.cpassword)
            {
                appTransaction.Status = 0;
                appTransaction.Message = "Confirm Password Does Not Match";
                return Json(appTransaction);
            }
            else
            {
                Connection.Execute("Update tblMaster_Customer SET Password='" + changePassword.password + "' where ID='" + SessionHelper.CustomerID + "'");
                appTransaction.Status = 1;
                appTransaction.Message = "Password Successfully Update";
                Session.Contents.RemoveAll();
                return Json(appTransaction);
            }
        }
        [Route("My-Order")]
        public ActionResult MyOrder()
        {
            if (SessionHelper.Islogin == false)
            {
                return Redirect("/Home");
            }
            List<MyOrderModel> myOrders = new List<MyOrderModel>();
            myOrders = repo.GetMyOrder().FindAll(e=>e.CustomerID==SessionHelper.CustomerID);
            return View(myOrders);
        }
        [Route("Order-Product/{id}")]
        public ActionResult OrderProduct(int id)
        {
            List<OrderProductReport> orderProducts = new List<OrderProductReport>();
            orderProducts = Connection.Query<OrderProductReport>("Exec ProcManage_Report 'OrderReportWithProduct','" + id + "'").ToList();
            if (orderProducts.Count <= 0)
            {
                orderProducts = new List<OrderProductReport>();
            }
            return View(orderProducts);
        }
        [Route("Invoice/{id}")]
        public ActionResult Invoice(int id)
        {
            if (SessionHelper.Islogin == false)
            {
                return Redirect("/Home");
            }
            InvoiceModel invoice = new InvoiceModel();
            invoice = Connection.Query<InvoiceModel>("Proc_GetInvoice 'GetDetail','"+id+"'").FirstOrDefault();
            invoice.products=Connection.Query<InvoiceProduct>("Proc_GetInvoice 'InvoiceProduct','" + id + "'").ToList();
            return View(invoice);
        }
    }
}

HelpOn/Views/MyProfile/ChangePassword.cshtml
<div class="card">
    <div class="card-body">
        <h6>Change Password</h6>
        <hr />
        <form action="/ChangePasswordSubmit" method="post" id="formChangePassword">
            <label>OLD Password</label>
            <input type="text" name="OldPassword" placeholder="Enter Old Password"  />
            <label>New Password</label>
            <input type="password" name="password" placeholder="***********"  />
            <label>Confirm Password</label>
            <input type="password" name="cpassword" placeholder="***********" />
            <br />
            <input type="submit" class="btn btn-success mt-2" value="Change Password" />
        </form>
    </div>
</div>
<script>
    $("#formChangePassword").submit(function (e) {
        e.preventDefault(e);
        var url = $('#formChangePassword')[0].action;
        $.ajax({
            type: "POST",
            url: url,
            data: $('#formChangePassword').serialize(),
            success: function (data) {
                if (data.Status > 0) {
                    swal('Alert', data.Message, 'success').then((value) => { location.reload(); });
                }
                else {
                    swal('Alert', data.Message, 'error');
                }
            },
            error: function (xhr, status, error) {
                alert(error);
            }
        })
    });
</script>

HelpOn/Views/MyProfile/Index.cshtml
@model HelpOn.Models.CustomerModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container pt-4">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6>Personal Detail</h6>
                    <form action="/UpdateProfile" method="post" id="formUpdateProfile">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Name</label>
                                <input type="text" name="Name" placeholder="Enter Your Name" value="@Model.Name" />
                            </div>
                            <div class="col-md-6">
                                <label>Email</label>
                                <input type="email" name="Email" placeholder="Enter Email" value="@Model.Email" />
                            </div>
                            <div class="col-md-12">
                                <label>Mobile</label>
                                <input type="number" name="Mobile" placeholder="Enter Mobile" readonly="readonly" value="@Model.Mobile" />
                            </div>
                            <div class="col-md-6">
                                <label>State</label>

                                @Html.DropDownListFor(M => M.StateID, new SelectList(Model.State, "Value", "Text"), "--Select--", new { @class = "form-control ddlState" })

                            </div>
                            <div class="col-md-6">
                                <label>City</label>
                                <select class="form-control" id="ddlCity" name="CityID" value="@Model.CityID"></select>
                            </div>
                            <div class="col-md-12">
                                <label>Pin code</label>
                                <input type="number" class="form-control" name="Pincode" value="@Model.Pincode" />
                            </div>
                            <div class="col-md-12">
                                <label>Address</label>
                                <textarea class="form-control" name="Address">@Model.Address</textarea>
                            </div>

                            <div class="col-md-12">
                                <br />
                                <input type="submit" class="btn btn-success" value="Submit" />
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
        <div class="col-md-6">
            @Html.Action("ChangePassword", "MyProfile")
        </div>

    </div>
</div>
<script>

    $("#StateID").change(function () {
        var id = $(this).val();
        GetCity(id);
    });
    function GetCity(e) {
                var cityid = '@Model.CityID';
        $.ajax({
            type: "POST",
            url: '@Url.Action("getCity", "MyProfile")',
            data: { stateId: e },
            success: function (data) {
                var items = [];
                items.push("<option>--Choose Your City--</option>");
                $.each(data, function () {
                    if (cityid == this.ID) {
                        items.push("<option selected='selected' value=" + this.ID + ">" + this.Name + "</option>");
                    }
                    else {
                        items.push("<option value=" + this.ID + ">" + this.Name + "</option>");
                    }

                });
                $("#ddlCity").html(items.join(' '));
            }
        });

    }
    $(".ddlState").each(function () {

        var id = $(this).val();
        var stateid = $("#StateID").val();
        if (id == stateid) {
            GetCity(id);
        }
    });
    $("#formUpdateProfile").submit(function (e) {
        e.preventDefault(e);
        var url = $('#formUpdateProfile')[0].action;
        $.ajax({
            type: "POST",
            url: url,
            data: $('#formUpdateProfile').serialize(),
            success: function (data) {
                if (data.Status > 0) {
                    swal('Alert', data.Message, 'success').then((value) => { location.reload(); });

                }
                else {
                    swal('Alert', data.Message, 'error');
                }
            },
            error: function (xhr, status, error) {
                alert(error);
            }
        })
    });
</script>

HelpOn/Views/MyProfile/MyOrder.cshtml
@model List<HelpOn.Models.MyOrderModel>
@{
    ViewBag.Title = "MyOrder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container pt-4">
    <div class="card">
        <div class="card-body table-responsive">
            <h6>My Order</h6>
            <hr />
            @if (Model.Count > 0)
            {
                <table class="table">
                    <tr>
                        <th>Date</th>
                        <th>Order Status</th>
                        <th>Merchant</th>
                        <th>Shop Address</th>
                        <th>Payment Mode</th>
                        <th>Shipping Address</th>
                        <th>View</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <label>@item.OrderDate</label>
                            </td>
                            <td>
                                @if (item.OrderStatus.ToString().ToUpper() == "Shipped".ToUpper())
                                {
                                    <label class="alert alert-info">@item.OrderStatus</label>
                                    <br />
                                    <label>@item.ShippedRemark</label>
                                }
                                else if (item.OrderStatus.ToString().ToUpper() == "Delivered".ToUpper())
                                {
                                    <label class="alert alert-success">@item.OrderStatus</label>
                                    <button type="button" onclick="location.replace('/Invoice/@item.ID')">Invoice</button>
                                    <br />
                                    <label>@item.DeliveredRemark</label>
                                }
                                else if (item.OrderStatus.ToString().ToUpper() == "Cancelled".ToUpper())
                                {
                                    <label class="alert alert-danger">@item.OrderStatus</label>
                                    <br />
                                    <label>@item.CancelRemark</label>
                                }
                                else
                                {
                                    <label class="alert alert-primary">@item.OrderStatus</label>
                                }

                            </td>
                            <td>
                                <h6> @item.ShopName</h6>
                                <label>@item.MerchantName</label>
                            </td>
                            <td>
                                <label>@item.MerchantAddress</label>
                            </td>
                            <td>
                                <label> @item.PaymentMode</label>
                                <br />
                                <label> @item.UPI</label>
                                <br />
                                <label> @item.TransactionNo</label>
                                @if (item.ScreenShot.ToString().Length>40)
                                {
                                    <br />
                                    <a href="@item.ScreenShot">Screen Shot</a>
                                }
                            </td>
                            <td>
                                <label>
                                    @item.ShippingAddress
                                </label>
                            </td>
                            <td>
                                @*<a href="/Order-Product/@item.ID" class="btn bg-success text-white font-weight-bold">View Product</a>*@
                                <button type="button" data-toggle="collapse" data-target="#collapseProduct_@item.ID" aria-expanded="false" aria-controls="collapseProduct_@item.ID">
                                    Product
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="7">
                                <div class="collapse" id="collapseProduct_@item.ID">
                                    <div class="card card-body">
                                        @if (item.productReports.Count > 0)
                                        {
                                            <table class="table">
                                                <tr>

                                                    <th>Photo</th>
                                                    <th>Product</th>
                                                    <th>Amount</th>
                                                    <th>Total Amount</th>
                                                </tr>
                                                @foreach (var product in item.productReports)
                                                {


                                                    <tr>

                                                        <td style="width:150px;">
                                                            <img src='@product.IMG1' width="100%" />
                                                        </td>
                                                        <td>
                                                            <label>@product.ProductName x @product.Qty</label>
                                                        </td>
                                                        <td>
                                                            <label> @product.Amount</label>
                                                        </td>
                                                        <td>
                                                            <label>
                                                                @product.NetAmount
                                                            </label>
                                                        </td>

                                                    </tr>
                                                }
                                            </table>


                                        }
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                </table>


            }
            else
            {
                <a href="/" class="btn btn-success">Continue Shopping</a>
            }

        </div>
    </div>
</div>

HelpOn/Views/MyProfile/OrderProduct.cshtml
@model List<HelpOn.Models.OrderProductReport>
@{
    ViewBag.Title = "OrderProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container pt-4">
    <div class="card">
        <div class="card-body table-responsive">
            <h6>My Order</h6>
            <hr />
            @if (Model.Count > 0)
            {
                <table class="table">
                    <tr>
                        <th>Status</th>
                        <th>Photo</th>
                        <th>Product</th>
                        <th>Amount</th>
                        <th>Total Amount</th>
                    </tr>
                    @foreach (var item in Model)
                    {


                        <tr>
                            <td>
                                @if (item.OrderStatus.ToString().ToUpper() == "Shipped".ToUpper())
                                {
                                    <label class="alert alert-info">@item.OrderStatus</label>
                                }
                                else if (item.OrderStatus.ToString().ToUpper() == "Delivered".ToUpper())
                                {
                                    <label class="alert alert-success">@item.OrderStatus</label>
                                }
                                else if (item.OrderStatus.ToString().ToUpper() == "Cancelled".ToUpper())
                                {
                                    <label class="alert alert-danger">@item.OrderStatus</label>
                                }
                                else
                                {
                                    <label class="alert alert-primary">@item.OrderStatus</label>
                                }

                            </td>
                            <td style="width:150px;">
                                <img src='@item.IMG1' width="100%" />
                            </td>
                            <td>
                                <label>@item.ProductName x @item.Qty</label>
                            </td>
                            <td>
                                <label> @item.Amount</label>
                            </td>
                            <td>
                                <label>
                                    @item.NetAmount
                                </label>
                            </td>

                        </tr>
                    }
                </table>


            }
            else
            {
                <a href="/" class="btn btn-success">Continue Shopping</a>
            }

        </div>
    </div>
</div>

HelpOn/Views/MyProfile/invoice.cshtml
@model HelpOn.Models.InvoiceModel
@{
    ViewBag.Title = "invoice";
    Layout = null;
}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" />
<style>
    .invoice-title h2, .invoice-title h3 {
        display: inline-block;
    }

    .table > tbody > tr > .no-line {
        border-top: none;
    }

    .table > thead > tr > .no-line {
        border-bottom: none;
    }

    .table > tbody > tr > .thick-line {
        border-top: 2px solid;
    }
</style>
<div class="container">
    <div class="row">

        <div class="col-xs-12">
            <div class="invoice-title">
                <h2>

                    <img src="~/assets/icon.jpg" style="width: 50px;" />
                    Help on
                </h2>
                <h3 class="pull-right">Order #@Model.InvoiceNo</h3>
            </div>
            <hr>
            <div class="row">
                <div class="col-xs-6">
                    <address>
                        <strong>Billed To:</strong><br>
                        <b>@Model.ShopName</b><br>
                        @Model.MerchantAddress<br>
                        Pin @Model.Pincode india<br>
                        Phone. No. @Model.Merchantmobile<br>
                    </address>
                </div>
                <div class="col-xs-6 text-right">
                    <address>
                        <strong>Shipped To:</strong><br>
                        <b>@Model.CustomerName</b><br>
                        <p style="margin: 0;">@Model.ShippingAddress</p>

                    </address>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6">
                    <address>
                        <strong>Payment Method:</strong>
                        <b>@Model.PaymentMode</b>
                        @Model.TransactionNo
                    </address>
                </div>
                <div class="col-xs-6 text-right">
                    <address>
                        <strong>Order Date:</strong><br>
                        @Model.AddDate<br>
                        <br>
                    </address>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><strong>Order summary</strong></h3>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-condensed">
                            <thead>
                                <tr>
                                    <td><strong>Item</strong></td>
                                    <td class="text-center"><strong>Price</strong></td>
                                    <td class="text-center"><strong>Quantity</strong></td>
                                    <td class="text-right"><strong>Total</strong></td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.products)
                                {
                                    <tr>
                                        <td>@item.Name</td>
                                        <td class="text-center">@item.Amount</td>
                                        <td class="text-center">@item.Qty</td>
                                        <td class="text-right">@item.NetAmount</td>
                                    </tr>

                                }


                                <tr>
                                    <td class="thick-line"></td>
                                    <td class="thick-line"></td>
                                    <td class="thick-line text-center"><strong>Subtotal</strong></td>
                                    <td class="thick-line text-right">@Model.TotalAmount</td>
                                </tr>
                                <tr>
                                    <td class="no-line"></td>
                                    <td class="no-line"></td>
                                    <td class="no-line text-center"><strong>Discount</strong></td>
                                    <td class="no-line text-right">@Model.Discount</td>
                                </tr>
                                <tr>
                                    <td class="no-line"></td>
                                    <td class="no-line"></td>
                                    <td class="no-line text-center"><strong>Total</strong></td>
                                    <td class="no-line text-right">
                                        @if (Model.PaybleAmount > 0)
                                        {
                                            <span>@Model.PaybleAmount</span>
                                        }
                                        else
                                        {
                                            <span>@Model.TotalAmount</span>
                                        }
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
window.print();

</script>