HelpOn/Controllers/HomeController.cs
using HelpOn.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HelpOn.Repository;
using HelpOn.Helper;
using System.Data;

namespace HelpOn.Controllers
{
    public class HomeController : Controller
    {
        LoginRepository repo = new LoginRepository();
        Cls_Connection cons = new Cls_Connection();
        public ActionResult Index()
        {
            HomeModel home = new HomeModel();
            home = repo.GetHomeDetail();
            return View(home);
        }
        [HttpPost]
        public JsonResult RequestForm(RequestForm request)
        {
            AppTransactionMessage appTransaction = new AppTransactionMessage();
            if (request.Name == "" || request.Name == null)
            {
                appTransaction.Status = 0;
                appTransaction.Message = "Enter Name";
                return Json(appTransaction);
            }
            else if (request.Mobile == "" || request.Mobile == null)
            {
                appTransaction.Status = 0;
                appTransaction.Message = "Enter Mobile";
                return Json(appTransaction);
            }
            else if (request.Email == "" || request.Email == null)
            {
                appTransaction.Status = 0;
                appTransaction.Message = "Enter Email";
                return Json(appTransaction);
            }
            else if (request.Service == "" || request.Service == null)
            {
                appTransaction.Status = 0;
                appTransaction.Message = "Enter Your Service";
                return Json(appTransaction);
            }
            else if ((Connection.ExecuteScalar<int>("select Count(*) from tblManage_RequestService where Mobile='" + request.Mobile + "'")) > 0)
            {
                appTransaction.Status = 0;
                appTransaction.Message = "Mobile Number Already Requested";
                return Json(appTransaction);
            }
            Connection.Execute("insert into tblManage_RequestService(Name,Email,Mobile,Service)values(N'" + request.Name + "','" + request.Email + "','" + request.Mobile + "',N'" + request.Service + "')");
            appTransaction.Status = 1;
            appTransaction.Message = "Successfully Submited Your Request";
            return Json(appTransaction);
        }
        public ActionResult _TopHeader()
        {
            WebColor web = new WebColor();
            web = Connection.Query<WebColor>("ProcManage_WebColor 'GetForTopHeader'").FirstOrDefault();
            web.Name = Connection.ExecuteScalar<string>("select Name from tblMaster_Customer where ID='" + SessionHelper.CustomerID + "'");
            web.Wallet = Connection.ExecuteScalar<string>("select Balance from tblAccount_Customer where CustomerID='" + SessionHelper.CustomerID + "'");
            return PartialView("_TopHeader", web);
        }
        [Route("about-us")]
        public ActionResult About()
        {
            return View();
        }
        [Route("Privacy-Policy")]
        public ActionResult PrivacyPolicy()
        {

            return View();
        }
        [Route("Coming-Soon")]
        public ActionResult ComingSoon()
        {

            return View();
        }
        [Route("Terms-and-Conditions")]
        public ActionResult TermsandConditions()
        {

            return View();
        }
        [Route("Disclaimer")]
        public ActionResult Disclaimer()
        {

            return View();
        }
        [Route("Segments")]
        public ActionResult AllCategory()
        {
            List<CategoryModel> categories = new List<CategoryModel>();
            categories = repo.GetCategory("GetCategory").FindAll(e => e.Type == "Main");
            return View(categories);
        }


        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult SideDropDownMenu()
        {
            List<CategoryModel> categories = new List<CategoryModel>();
            categories = repo.GetCategory("GetCategory");
            if (categories.Count <= 0)
            {
                categories = new List<CategoryModel>();
            }
            return PartialView("SideDropDownMenu", categories);
        }
        public ActionResult Search()
        {
            List<string> str = new List<string>();
            str = Connection.Query<string>("ProcGet_List 'GetforSearch'").ToList();
            var text = string.Join("|", str);
            ViewBag.Search = text;
            List<string> states = new List<string>();
            states = Connection.Query<string>("ProcGet_List 'GetLocationforSearch'").ToList();
            var state = string.Join("|", states);
            ViewBag.State = state;
            return PartialView("Search");
        }
        [Route("Logout")]
        public ActionResult Logout()
        {
            Session.RemoveAll();
            return Redirect("/Home");
        }
        public ActionResult GetallCategoryFirst(long CId)
        {
            DataSet dsRecord = new DataSet();
            CategoryModel resultSet = new CategoryModel();
            try
            {
                string sQryeraw = string.Format(@"Exec ProcMaster_Category Getcatname,@ID='" + CId + "' ");
                dsRecord = cons.GetDataSet(sQryeraw);
                resultSet.Name = Convert.ToString(dsRecord.Tables[0].Rows[0]["Name"].ToString());
                resultSet.subcateName = (from item in dsRecord.Tables[1].AsEnumerable()
                                          select new SubCategory
                                          {
                                              SubCatId = Convert.ToInt16(item.Field<int>("ID")),
                                              SubCatName = Convert.ToString(item.Field<string>("Name")),
                                          }).ToList();
            }
            catch (Exception ex)
            {
            }
            return Json(resultSet);
        }

        [Route("mobilesearch")]
        public ActionResult MobileSearch()
        {

            return View();
        }
    }
}

HelpOn/Controllers/MerchantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using HelpOn.Helper;
using HelpOn.Models;
using HelpOn.Repository;

namespace HelpOn.Controllers
{
    public class MerchantController : Controller
    {
        LoginRepository repo = new LoginRepository();
        // GET: Merchant
        [Route("Segment/{Name}")]
        public ActionResult Index(string Name)
        {
            MerchantViewModel merchantView = new MerchantViewModel();
            merchantView.Merchants = repo.GetMerchant().FindAll(e => (e.CategoryName == Name.Replace("-", " ").Replace("_", "&") || e.SubCategoryName.Trim() == Name.Replace("-", " ").Replace("_", "&").Trim()) || (e.StateName.Trim() == Name.Replace("-", " ").Replace("_", "&").Trim() || e.Districtname.Trim() == Name.Replace("-", " ").Replace("_", "&").Trim()));
            if (merchantView.Merchants.Count <= 0)
            {
                merchantView.Merchants = new List<MasterMerchant>();
            }
            merchantView.SubCategory = repo.GetCategory("GetSubCategory").FindAll(e => e.CName.Trim() == Name.Replace("-", " ").Replace("_", "&").Trim() && e.Type == "Main");
            if (merchantView.SubCategory.Count <= 0)
            {
                merchantView.SubCategory = new List<CategoryModel>();
            }

            ViewBag.CategoryName = Name.Replace("-", " ").Replace("_", "&");
            return View(merchantView);
        }
        [Route("Popular/{Name}")]
        public ActionResult Popular(string Name)
        {
            MerchantViewModel merchantView = new MerchantViewModel();
            List<MasterMerchant> merchants = new List<MasterMerchant>();
            merchantView.Category = Connection.Query<CategoryModel>("Exec ProcGet_List 'GetCategoryByTopCategory',0,'" + Name.Replace("-", " ").Replace("_", "&").Trim() + "'").ToList();
            if (merchantView.Category.Count <= 0)
            {
                merchantView.Category = new List<CategoryModel>();
                merchantView.SubCategory = Connection.Query<CategoryModel>("Exec ProcGet_List 'GetSubCategoryByTopCategory',0,'" + Name.Replace("-", " ").Replace("_", "&").Trim() + "'").ToList();
            }

            if (merchantView.SubCategory != null)
            {
                if (merchantView.SubCategory.Count <= 0)
                {
                    merchantView.SubCategory = new List<CategoryModel>();
                    merchantView.Merchants = Connection.Query<MasterMerchant>("Exec ProcGet_List 'GetMerchantByTopCategory',0,'" + Name.Replace("-", " ").Replace("_", "&").Trim() + "'").ToList();
                }
                else
                {
                    merchantView.Merchants = new List<MasterMerchant>();
                }
            }
            else
            {
                merchantView.Merchants = new List<MasterMerchant>();
                merchantView.SubCategory = new List<CategoryModel>();
            }
            if (merchantView.Merchants.Count <= 0)
            {
                merchantView.Merchants = new List<MasterMerchant>();
            }

            ViewBag.CategoryName = Name.Replace("-", " ").Replace("_", "&");
            return View(merchantView);
        }
        [Route("Detail/{id}")]
        public ActionResult MerchantDetail(int id)
        {
            MerchantDetailModel merchant = new MerchantDetailModel();
            ViewBag.MID = id;
            merchant = repo.GetMerchantDetail(id);
            if (merchant == null)
            {
                merchant = new MerchantDetailModel();
            }
            return View(merchant);
        }
        [Route("Gallery/{id}")]
        public ActionResult Gallery(int id)
        {
            List<GalleryModel> merchant = new List<GalleryModel>();
            merchant = Connection.Query<GalleryModel>("ProcGet_List 'GetGallery','" + id + "'").ToList();
            if (merchant == null)
            {
                merchant = new List<GalleryModel>();
            }
            return View(merchant);
        }
        [Route("Product/{id}")]
        public ActionResult ProductDetail(int id)
        {

            ProductDetailModel productDetail = new ProductDetailModel();
            productDetail.product = repo.GetMerchantProduct().FindAll(e => e.ID == id).FirstOrDefault();
            ViewBag.MID = productDetail.product.MID;
            ViewBag.Itemshow = 0;
            return View(productDetail);
        }
        public ActionResult _ReletiveProduct(int id)
        {
            ProductDetailModel productDetail = new ProductDetailModel();
            productDetail.product = repo.GetMerchantProduct().FindAll(e => e.ID == id).FirstOrDefault();

            List<ProductModel> Reletedproduct = repo.GetMerchantProduct().FindAll(e => (e.CID == productDetail.product.CID || e.SCID == productDetail.product.SCID) && e.MID == productDetail.product.MID);
            List<CartModel> cart = repo.GetCart(productDetail.product.MID, SessionHelper.CustomerID);

            ViewBag.CartItem = cart.Count;
            return PartialView(Reletedproduct);
        }

        public ActionResult _MerchantProduct(int id, int cid = 0, string name = "")
        {

            List<ProductModel> products = new List<ProductModel>();
            products = repo.GetMerchantProduct().FindAll(e => (e.MID == id && (e.CID == cid || (cid) == 0) && (e.Name == name || (name) == ""))).Take(15).ToList();
            List<CartModel> cart = repo.GetCart(id, SessionHelper.CustomerID);
            ViewBag.Itemshow = products.Count();
            ViewBag.CartItem = cart.Count;
            if (products.Count <= 0)
            {
                products = new List<ProductModel>();
            }

            return PartialView("_MerchantProduct", products);
        }
        public ActionResult _MerchantMoreProduct(int id, int cid = 0, string name = "")
        {

            List<ProductModel> products = new List<ProductModel>();
            products = repo.GetMerchantProduct().FindAll(e => (e.MID == id && (e.CID == cid || (cid) == 0) && (e.Name == name || (name) == ""))).ToList();
            List<CartModel> cart = repo.GetCart(id, SessionHelper.CustomerID);
            ViewBag.Itemcount = products.Count();
            ViewBag.CartItem = cart.Count;
            if (products.Count <= 0)
            {
                products = new List<ProductModel>();
            }

            return PartialView("_MerchantProduct", products);
        }
        public ActionResult _MerchantProductByCategory(int id)
        {

            List<CategoryModel> categories = Connection.Query<CategoryModel>("select * from tblMaster_Category where Type='Ecommerce' and ID IN(select DISTINCT CID from tblManage_MerchantProduct where MID='" + id + "')").ToList();
            if (categories.Count <= 0)
            {
                categories = new List<CategoryModel>();
            }
            List<string> str = new List<string>();
            str = Connection.Query<string>("select Name from tblManage_MerchantProduct where MID='" + id + "'").ToList();
            var text = string.Join("|", str);
            ViewBag.ProductSearch = text;
            return PartialView("_MerchantProductByCategory", categories);
        }

        public ActionResult _Appointments(int id)
        {
            ViewBag.MID = id;
            return PartialView("_Appointments", null);
        }
        public ActionResult _Review(int id)
        {
            ViewBag.MID = id;
            List<ListReview> reviews = new List<ListReview>();
            reviews = Connection.Query<ListReview>("Exec ProcManage_Report 'MerchantReview'").ToList().FindAll(e => e.MID == id);
            if (reviews.Count <= 0)
            {
                reviews = new List<ListReview>();
            }
            return PartialView("_Review", reviews);
        }
        public ActionResult _EnquiryNow(int id)
        {
            ViewBag.MID = id;
            return PartialView("_EnquiryNow", null);
        }
        [HttpPost]
        [Route("Submit_Appointments")]
        public JsonResult Submit_Appointments(AppointmentsModel appointments)
        {
            AppTransactionMessage appTransaction = new AppTransactionMessage();
            // appTransaction = Connection.Query<AppTransactionMessage>("Exec ProcManage_AppointMentAndEquiry 'insert','" + appointments.MID + "','" + appointments.Name + "','" + appointments.Mobile + "','" + appointments.Email + "','" + appointments.AppointmentsDate + "','" + appointments.AppointmentsTime + "','" + appointments.Description + "','" + appointments.Type + "'").FirstOrDefault();
            DynamicParameters parameters = new DynamicParameters();
            parameters.Add("@Action", "insert");
            parameters.Add("@MID", appointments.MID);
            parameters.Add("@Name", appointments.Name);
            parameters.Add("@Mobile", appointments.Mobile);
            parameters.Add("@Email", appointments.Email);
            parameters.Add("@AppointmentsDate", appointments.AppointmentsDate);
            parameters.Add("@AppointmentsTime", appointments.AppointmentsTime);
            parameters.Add("@Description", appointments.Description);
            parameters.Add("@Type", appointments.Type);
            appTransaction = Connection.ReturnList<AppTransactionMessage>("ProcManage_AppointMentAndEquiry", parameters).FirstOrDefault();
            return Json(appTransaction);
        }
        [Route("GetMerchantBySearch")]
        public ActionResult GetMerchantBySearch(SearchModel search)
        {
            List<MasterMerchant> merchants = new List<MasterMerchant>();
            merchants = Connection.Query<MasterMerchant>("Exec ProcGet_List 'GetBySearch',0,'" + search.Name + "','" + search.State + "','"+search.TopCategoryID+"'").ToList();
            if (merchants.Count <= 0)
            {
                merchants = new List<MasterMerchant>();
            }

HelpOn/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<section class="section_all bg-light" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section_title_all text-center">
                    <h3 class="font-weight-bold">Welcome To Helpon</h3>
                    <p class="section_subtitle mx-auto text-muted">
                        Our Mission is to Empower Small Businesses to Achieve Success
                    </p>

                </div>
            </div>
        </div>
        <div class="row vertical_content_manage mt-5">
            <p><b>HELPON</b> is a leading digital E-Commerce & search engine platform for domestic service businesses in All india.</p>
            <pre>
                <b>Helpon</b> is one of the leading online resources dedicated to small business. We deliver products, services and educational opportunities that are effective, easy to understand and geared to help business owners become more competitive in their respective industries.

                The HELPON.IN. Business profile boasts millions of unique visitors every month who search our comprehensive database for individual businesses and Google, industry segments and geographic-specific listings. Business owners can customize their page to improve online visibility and marketability, gain key knowledge vital for success, and find products to help grow and manage their business. The HELPON team works hard to deliver helpful news and advice, promotion opportunities and tools for small businesses.

                <b>Our</b> close relationship with entrepreneurs allows us to gather and share key insights about this very important market sector to a wider audience. We are constantly evolving and improving, and our mission to empower small businesses continues to be inspired by their significant impact on an individual, local and national level.
                <b>You</b> can do all this here at a website & Mobile Application that begins with a very simple and modest design to use and will continuously look forward for development opportunities to serve you better...

                Thanks Team,
                Helpon

</pre>
        </div>

    </div>
</section>

HelpOn/Views/Home/AllCategory.cshtml
@model List<HelpOn.Models.CategoryModel>
@using HelpOn.Helper
@{
    ViewBag.Title = "AllCategory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="section-padding">
    <div class="container">

        <h4 style="font-family: 'Libre Baskerville', serif;">All Segments</h4>
        <div class="products column-6 mobile-column-2">
            
            @foreach (var Categoryitem in Model)
            {

                
                    <div class="product product-type-simple">

                        <div class="product-wrapper product-type-1">

                            <div class="content-wrapper p-0">
                                <h3 class="product-title text-center p-2" style="background: @Categoryitem.BgColor;border-top-left-radius: 15px;border-top-right-radius: 15px;margin:0;"><a href="/Segment/@Categoryitem.Name.Trim().Replace(" ","-").Replace("&","_")" title="@Categoryitem.Name" style="font-family: 'Libre Baskerville', serif;color: @Categoryitem.FontColor;font-weight: bold;">@Categoryitem.Name</a></h3>
                            </div>
                            <div class="thumbnail-wrapper text-center p-0">
                                <a href="/Segment/@Categoryitem.Name.Trim().Replace(" ","-").Replace("&","_")">
                                    <img class="img-fluid item-img rounded" alt="@Categoryitem.Name" src="@Application.ImagePath/Category/@Categoryitem.IMG">

                                </a>
                            </div>
                        </div>

                    </div>
                   
            }
        </div>
    </div>
</section>

HelpOn/Views/Home/ComingSoon.cshtml
@{
    ViewBag.Title = "ComingSoon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img src="~/assets/comingsoon.jpg" style="width:100%;" />

HelpOn/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<!-- Javascript -->

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HelpOn/Views/Home/Disclaimer.cshtml
@{
    ViewBag.Title = "Disclaimer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="section_all bg-light" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section_title_all text-center">
                    <h3 class="font-weight-bold">Disclaimer</h3>

                </div>
            </div>
        </div>
        <div class="row vertical_content_manage mt-5">

            <pre>
                <h5>  About Us</h5>
                The domain name www.helpon.in (the “Website”) is owned and operated by Helpon Digital Services a Company incorporated under the provisions of the Companies Act, 2013, having its registered (hereinafter referred to as the “HELPON”, “we”, “Our”, “us”).
                We are providing E-market platform, Digital Infra-Structure branding, product promotion & marketing, and complete E-solution to its merchants (subscriber). Our platform creates a user interface that directly connects the user and merchant through that. The user can directly place it order or purchase goods or services from the merchants and directly make the payment to the merchants provided bank account. Any issues related to the return, refund or cancellation of ordered goods or services are directly settled by the user and merchant.

                <h5>Website Disclaimer</h5>
                The information contained on this website is for general information purposes only. The information is provided by [www.helpon.in], owned & operated by Helpon Digital Services. While we endeavour to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk.
                
                In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website.
                
                Through this website, you are able to link to other websites which are not under the control of Helpon Digital Services. We have no control over the nature, content, and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them.
               
                 Every effort is made to keep the website up and running smoothly. However, Helpon Digital Services takes no responsibility for, and will not be liable for, the website being temporarily unavailable due to the nature of the internet or any technical issues beyond our control.

                <h5>Logos and Trademarks Disclaimer</h5>

                All logos and trademarks of third parties referenced on www.helpon.in are the trademarks and logos of their respective owners. Any inclusion of such trademarks or logos does not imply or constitute any approval, endorsement, or sponsorship of Helpon Digital Services. by such owners.

                <h5>Contact Us</h5>

                If you have any feedback, comments, requests for technical support or other enquiries, please contact us by email: info@helpon.in


</pre>
        </div>

    </div>
</section>

HelpOn/Views/Home/MobileSearch.cshtml
@{
    ViewBag.Title = "MobileSearch";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="section-padding">
    <div class="container">
        <div class="row">
            <div class="column column-center">
                <div class="card">
                    <div class="card-body">
                        @Html.Action("Search", "Home")
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

HelpOn/Views/Home/PrivacyPolicy.cshtml
@{
    ViewBag.Title = "Privacy-Policy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="section_all bg-light" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section_title_all text-center">
                    <h3 class="font-weight-bold">Privacy Policy</h3>
                    
                </div>
            </div>
        </div>
        <div class="row vertical_content_manage mt-5">
           
            <pre>
                This privacy notice discloses the privacy practices for www.helpon.in This privacy notice applies solely to        information collected by this web site. It will notify you of the following: 

                What personally identifiable information is collected from you through the web site, how it is used and with whom it may be shared.
                What choices are available to you regarding the use of your data.

                The security procedures in place to protect the misuse of your information.
                
                Thanks Team,
                Helpon

</pre>
        </div>

    </div>
</section>

HelpOn/Views/Home/Search.cshtml
@model HelpOn.Models.SearchModel
@using (Html.BeginForm("GetMerchantBySearch", "Merchant", FormMethod.Post, new { id = "Experience" }))
{
    <div class="input-group">
        <div class="input-group-prepend">
            <div class="input-group-prepend">
                <button type="button" class="klbth-icon-location bg-info"></button>
            </div>
           
            <input type="text" class="border-right Sugetionbox" id="SearchlocationAutofill" data-autofill-values="@ViewBag.State" name="State" placeholder="Search State" style="background-color: #cfcece;color: #000;" />
        </div>
        <input id="myAutocomplete" class="Sugetionbox" type="text" placeholder="Search for anything, anywhere" data-autofill-values="@ViewBag.Search" name="Name" autocomplete="off" style="font-family: 'Libre Baskerville', serif; border-radius: unset;">
        <div class="input-group-prepend">
            <button type="submit" class="bg-info">Search</button>
        </div>
    </div>
}

HelpOn/Views/Home/SideDropDownMenu.cshtml
@model List<HelpOn.Models.CategoryModel>
@using HelpOn.Helper
<ul id="menu-sidebar-menu-1" class="menu-list">
    @{ int i = 0;}
    @foreach (var item in Model)
    {
        i++;
        if (i <= 12)
        {
            <li style="font-family: 'Libre Baskerville', serif;" class="text-capitalize category-parent  menu-item menu-item-type-taxonomy menu-item-object-product_cat current-product-ancestor current-menu-parent current-product-parent">
                <a href="/Segment/@item.Name.Trim().Replace(" ","-").Replace("&","_")">
                    <img src="@Application.ImagePath/Category/@item.IMG" alt="@item.Name" style="width: 20px;height:20px"> <span style="margin-left: 10px;"> @item.Name</span>

                </a>
            </li>
        }

    }
    <li style="font-family: 'Libre Baskerville', serif;" class="text-capitalize category-parent  menu-item menu-item-type-taxonomy menu-item-object-product_cat current-product-ancestor current-menu-parent current-product-parent"><a href="/Segments"> <i class="klbth-icon-right-arrow"></i><span style="margin-left: 10px;"> More...</span></a></li>
</ul>

HelpOn/Views/Home/_Search.cshtml
@{
    ViewBag.Title = "_Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form class="dgwt-wcas-search-form" role="search" action="/search" method="get">
    <div class="dgwt-wcas-sf-wrapp autocomplete">
        <svg version="1.1" class="dgwt-wcas-ico-magnifier" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 51.539 51.361" enable-background="new 0 0 51.539 51.361" xml:space="preserve">
<path fill="#444" d="M51.539,49.356L37.247,35.065c3.273-3.74,5.272-8.623,5.272-13.983c0-11.742-9.518-21.26-21.26-21.26 S0,9.339,0,21.082s9.518,21.26,21.26,21.26c5.361,0,10.244-1.999,13.983-5.272l14.292,14.292L51.539,49.356z M2.835,21.082 c0-10.176,8.249-18.425,18.425-18.425s18.425,8.249,18.425,18.425S31.436,39.507,21.26,39.507S2.835,31.258,2.835,21.082z"></path>
</svg>
        <label class="screen-reader-text" for="dgwt-wcas-search-input-1">Search Store</label>
        <input id="myInput" type="search" class="dgwt-wcas-search-input" name="search" value="" placeholder="Search for Products , Shops..." autocomplete="off" style="font-family: 'Libre Baskerville', serif;">

    </div>
</form>